name = "gts"
version = "0.0.1"
description = "Opinionated bindings to erlang's ets tables."
target = "erlang"
licences = ["GPLv2"]
repository = { type = "github", user = "lunarmagpie", repo = "gts" }
links = [{ title = "Website", href = "https://github.com/lunarmagpie/gts" }]

[dependencies]
gleam_stdlib = "~> 0.28"
gleam_erlang = "~> 0.18"

[dev-dependencies]
gleeunit = "~> 0.10"
